/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Create diagrams',
      link: { type: 'doc', id: 'create/index' },
      items: [{ type: 'autogenerated', dirName: 'create/types' }],
    },
    {
      type: 'category',
      label: 'Style diagrams',
      link: { type: 'doc', id: 'style/presentation' },
      items: [{ type: 'autogenerated', dirName: 'style/types' }],
    },
    {
      type: 'category',
      label: 'Save and share',
      items: [
        'collaboration/sharing',
        'collaboration/encryption',
        'collaboration/working-and-saved-state',
      ],
    },
  ],
}

export default sidebars
